spring.application.name=backProyectoPoligamia



spring.datasource.url=jdbc:postgresql://localhost:5432/poligamia
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8084

#configuracion JWT
jwt.secret=miClaveSecretaParaPoligamiaQueDebeTenerAlMenos32Caracteres